from logger import logger
from fastapi import Request


async def custom_middleware(request: Request, call_next):
    """
    Custom middleware to log request and response details.

    This middleware function logs details about incoming requests, including method, URL, headers,
    query parameters, and request body. It then forwards the request to the next middleware or
    route handler and logs the response status code.

    Args:
        request (Request): The incoming request object.
        call_next (callable): The callback function to call the next middleware or route handler.

    Returns:
        Response: The response generated by the subsequent middleware or route handler.

    Raises:
        Exception: If an error occurs during request processing.

    Note:
        - This middleware is intended to be used as part of a FastAPI application pipeline.
        - It logs details about both successful and failed requests.
    """
    try:
        logger.info(f"Request received: {request.method} {request.url}")
        logger.info(f"Headers: {request.headers}")
        logger.info(f"Query Parameters: {request.query_params}")
        body = await request.body()
        logger.info(f"Request Body: {body.decode()}")

        response = await call_next(request)

        logger.info(f"Response: {response.status_code}")

        return response
    except Exception as e:
        logger.error(f"Error processing request: {str(e)}")
        raise
